version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
os: Visual Studio 2015
init:
  - cmd: rd /s /q %CHOCOLATEYINSTALL%
  - ps: iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
install:
  - cinst cmake -y
  - .\.appveyor\remove_python27_from_path.bat
  - set "PATH=%PATH%;C:\Python34"
  - python --version
  - python -m pip install -U setuptools pip
  - python -m pip install EmPy
  - python -m pip install trollius
  - mkdir build
  - cd build
  - mkdir src
  - cd src
  - python -c "import shutil; shutil.copytree('../..', './class_loader', ignore=shutil.ignore_patterns('build'))"
  - git clone https://github.com/ros/console_bridge.git -b ros2
  - git clone --depth 1 https://github.com/pocoproject/poco.git -b poco-1.6.1-release
  - mkdir ament
  - cd ament
  - git clone https://github.com/ament/ament_cmake.git
  - git clone https://github.com/ament/ament_package.git
  - git clone https://github.com/ament/ament_tools.git
  - git clone https://github.com/osrf/osrf_pycommon.git
  - git clone https://github.com/ament/gtest_vendor.git
  - git clone https://github.com/ament/gmock_vendor.git
  - cd ..\..\..
  - '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64'
  - set "PATH=%PATH%;C:\Python34"
build_script:
  - cd build
  - |
    python -u src\ament\ament_tools\scripts\ament.py build --build-tests --cmake-args -DENABLE_XML:BOOL=OFF -DENABLE_JSON:BOOL=OFF -DENABLE_MONGODB:BOOL=OFF -DENABLE_UTIL:BOOL=OFF -DENABLE_NET:BOOL=OFF -DENABLE_NETSSL:BOOL=OFF -DENABLE_CRYPTO:BOOL=OFF -DENABLE_DATA:BOOL=OFF -DENABLE_DATA_SQLITE:BOOL=OFF -DENABLE_DATA_MYSQL:BOOL=OFF -DENABLE_DATA_ODBC:BOOL=OFF -DENABLE_ZIP:BOOL=OFF -DENABLE_PAGECOMPILER:BOOL=OFF -DENABLE_PAGECOMPILER_FILE2PAGE:BOOL=OFF
  - python -u src\ament\ament_tools\scripts\ament.py test --skip-build --skip-install --only class_loader
deploy: off
