sudo: required
os:
  - linux
  - osx
dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic
env:
  global:
    - AMENT_WS=~/ament_ws
    - AMENT_WS_SRC=${AMENT_WS}/src
install:
  - make -f .travis/Makefile install_deps
script:
  - mkdir -p build/src/ament
  - cd build
  - touch AMENT_IGNORE
  # Fetch dependencies into the workspace
  - cd src/ament
  - git clone https://github.com/ament/ament_cmake.git
  - git clone https://github.com/ament/ament_package.git
  - git clone https://github.com/ament/ament_tools.git
  - git clone https://github.com/osrf/osrf_pycommon.git
  - git clone https://github.com/ament/gtest_vendor.git
  - git clone https://github.com/ament/gmock_vendor.git
  - cd ..
  - git clone https://github.com/ros/console_bridge.git -b ros2
  - cd ..
  # Link source into workspace's source space
  - ln -s $TRAVIS_BUILD_DIR ./src
  # Build
  - python3 -u ./src/ament/ament_tools/scripts/ament.py build --build-tests --ament-cmake-args -DPYTHON_VERSION=3 -- --end-with class_loader
  # Test
  - python3 -u ./src/ament/ament_tools/scripts/ament.py test --skip-build --skip-install --only class_loader
