language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install coverage nose flake8 mock
script:
  - PYTHONASYNCIODEBUG=1 python setup.py nosetests -s --with-coverage --cover-inclusive
notifications:
  email: false
